version: '3'

networks:
  traefik:
    external: true

services:
  traefik:
    image: 'traefik:v2.6.6'
    container_name: 'traefik'
    restart: always
    networks:
      - traefik
    ports:
      - 8081:8081
      - 80:80
      - 443:443
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./conf.d:/etc/traefik/conf.d
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

