global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
    forwardedHeaders:
      insecure: true
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    forwardedHeaders:
      insecure: true

  traefik:
    address: :8081


certificatesResolvers:
  default:
    acme:
      email: spam@imposibrus.space
      storage: /etc/traefik/conf.d/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

log:
#  level: DEBUG
#  filePath: log/traefik.log
#  format: json

accessLog:
#  filePath: /path/to/log/log.txt
  format: common

api:
  insecure: true
  dashboard: true

# Enable ping
#ping:
  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
#  entryPoint: traefik

providers:
  docker:
#    endpoint: tcp://10.10.10.10:2375
#    defaultRule: Host(`{{ normalize .Name }}.docker.localhost`)
    exposedByDefault: false
    network: traefik

  file:
    directory: /etc/traefik/conf.d

